rpc_queue:
  image: rabbitmq:3.5.6-management
  ports:
    - "15672:15672"
  labels:
    - "description=Queue server (with admin plugin)"


# accounts
storage_account:
  image: mongo:3.1
  ports:
    - "27017:27017"
  labels:
    - "description=Storage for account data"
  command: "mongod --nojournal --smallfiles"

service_account:
  image: navi7/harpc
  links:
    - "rpc_queue"
    - "storage_account"
  labels:
    - "description=User accounts"
  command: "/harpc/start_service.sh account rpc_queue 5672"
  environment:
    - RPC_QUEUE=amqp://guest:guest@rpc_queue:5672/


# products
storage_product:
  image: mongo:3.1
  ports:
    - "27018:27017"
  labels:
    - "description=Storage for product data"
  command: "mongod --nojournal --smallfiles"

service_product:
  image: navi7/harpc
  links:
    - "rpc_queue"
    - "storage_product"
  labels:
    - "description=Product definitions and quantities"
  volumes:
     - ./harpc:/harpc
  command: "/harpc/start_service.sh product rpc_queue 5672"
#  command: "tail -f /dev/null"
  environment:
    - RPC_QUEUE=amqp://guest:guest@rpc_queue:5672/


# warehouse
storage_warehouse:
  image: mongo:3.1
  ports:
    - "27019:27017"
  labels:
    - "description=Storage for product data"
  command: "mongod --nojournal --smallfiles"

service_warehouse:
  image: navi7/harpc
  links:
    - "rpc_queue"
    - "storage_warehouse"
  labels:
    - "description=Warehouse stuff"
  command: "/harpc/start_service.sh warehouse rpc_queue 5672"
  environment:
    - RPC_QUEUE=amqp://guest:guest@rpc_queue:5672/
